Repository team-cobee/cobee-client, pull requests merged in 2025-07, with the labels that each got.

#11 [FE/Feat] 룸메이트 구인글 작성 화면 구현
  App.tsx
  app/(tabs)/post.tsx
Labels: :sparkles: feat, 💚 혜진

#13 [Fe/Setting] issue template 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙️ chore, 💚 혜진

#17 Feat/#16/recruit post : 공통 컴포넌트 Layer 적용 및 구인글 페이지 구현
  App.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/account.tsx
  app/(tabs)/index.tsx
  app/(tabs)/post.tsx
  app/(tabs)/recruitPost.tsx
  app/_layout.tsx
  assets/images/chat.png
  assets/images/commentArrow.svg
  assets/images/home.png
  assets/images/makeComment.svg
  assets/images/map.png
  assets/images/postProfile.png
  assets/images/sendComment.png
  components/layout/MainLayout.tsx
  components/ui/BottomTabs.tsx
  package-lock.json
  package.json
Labels: :sparkles: feat, ⭐ style

#31 Fix/30 routing issue
  app/(tabs)/account.tsx
  app/(tabs)/publicProfile.tsx
  app/(tabs)/submissionList.tsx
  components/ui/BottomTabs.tsx
Labels: :bug: fix, ❤️ 주연
